### ISSUE TITLE
説明をコードの中に書いたら良い

### ISSUE THREAD

**Issue by Innovative-Ideas** [fuqunaga/SyncUtil#2]
発表会でスライドを見せてくれましたが、実際にその内容やドキュメンテーションをコードの中に書いたら、コードが読みやすくなると思っております。
例えば、SyncParamのクラス

> NetworkBehaviourでないクラスでも値を同期
> シーンにSyncParamManagerを置いておく
> SyncParamで同期するObjectとメンバ名を指定
> 複数インスタンスで個別の値には非対応
>  _key = target.GetType() +"/" + target.name + "/" + name;	
> SyncParamManagerがNetworkBehaviourになってて同期を肩代わり

あと、クラスの使い方を書けばよい。例えば、

> Objectとメンバ名を指定する方法は
GameObjectにSyncParamのComponentを追加して、
Unity EditorのInspectorで同期したいclassとメンバを指定することです。

「NetworkBehaviourでないクラスでも値を同期」をやりたかったが、
SyncParamのクラスの名前を忘れてしまったし、LibraryのExampleの中に役に立つものが見つけられません。スライドを見直してクラス名を見つけましたが、もっと直接な方法があればいいなぁと思っています。

スライードの内容をコードの中にコピー・ペストした方が良さそうです。

**Comment by fuqunaga** [comment]
シンプルであることは高機能であることと同じくらい大事であると思っています。
丁寧な説明は人によっては冗長であったりノイズになってしまうこともあるかと思います。
コードから読み取りにくい部分はコメントに書くようにしてますが、ほかにもsummaryくらいは足してもいいかなと思います。

READMEやwikiを充実させる方向には賛成です。
ちなみにSyncParamのExampleもSyncUtilExamples sceneに含まれていますよ😊
