### ISSUE TITLE
isSlaver

### ISSUE THREAD

**Issue by Innovative-Ideas** [fuqunaga/SyncUtil#4]
SyncNet.isSlaverの意味なんですが、
isSlaveに変更すればよいです。
slaverの意味は奴隷の主です。
slaveの意味は奴隷です。
clientのみの時は奴隷になるので、isSlaveを使えば正しいと思っています。

**Comment by fuqunaga** [comment]
賛成です
PullRequest お待ちしてます！

**Comment by Innovative-Ideas** [comment]
Pull Requestを作りました！
https://github.com/fuqunaga/SyncUtil/pull/5

**Comment by fuqunaga** [comment]
thanks for the PR!
